# wip
# name: My Workflow
# on:
#   push:
#     branches:
#       - 'master'
# env:
#   message: 'conversation'
#   my_token: ${{ secrets.GITHUB_TOKEN }}
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: ['18.x', '20.x']
#     steps:
#       - name: Checking out our code
#         uses: actions/checkout@master
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install dependencies
#         run: npm ci
        
#   my_job:
#     needs: my_build
#     container:
#       image: node:10.16-jessie
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
#       volumes:
#         - my_docker_volume:/volume_mount
#       options: --cpus 1
#     services:
#       redis:
#         image: redis
#         ports:
#           - 6379/tcp
